### ISSUE TITLE
Allow the JavaApplicationRunner class to be overridden for Java applications

### ISSUE THREAD

**Issue by thegridman** [coherence-community/oracle-bedrock#419]
When Bedrock launches a Java application it uses the com.oracle.bedrock.runtime.java.JavaApplicationRunner to run the actual main class. It should be possible to override the name of the launcher class that will be used as some applications may need to do initialisation prior to the JavaApplicationRunner being invoked.

**Comment by brianoliver** [comment]
The requirement for this is no longer valid.

**Comment by brianoliver** [comment]
While it's not required, this issue is actually fixed by #422
