### ISSUE TITLE
Use Thread's context ClassLoader instead of Class.forName

### ISSUE THREAD

**Issue by thegridman** [coherence-community/oracle-bedrock#420]
There are some places in Bedrock code that executes in a launched Java application's JVM where Class.forName() is called to load classes. This can break if the application code has changed the ClassLoader for the executing Thread and result in a ClassNotFoundException.

Instances of Class.forName() should be changed to use the current Thread's context ClassLoader in JavaApplicationRunner and AbstractRemoteChannel.

**Comment by brianoliver** [comment]
The requirement for this is no longer valid.
